export const enum LinkItemCode {
    Home = 0,
    Guide = 1,
    OnDemand = 2,
    MyTv = 3,
    Settings = 4,
    Search = 5,
    Channels = 6,
    NewShows = 7,
    NewMovies = 8,
    RecommendedShows = 9,
    RecommendedMovies = 10,
    SubGenres = 11,
    SubGenresContent = 12,
    Account = 13,
    Subscription = 14,
    Favorites = 15,
    Privacy = 16,
    About = 17,
    LogInSignIn = 18,
    Details = 19,
    Login = 20,
    Player = 22,
    DetailsSeries = 23,
    DetailsMovies = 24,
    DetailsPrograms = 25,

    ShowAllRecentChannels = 26,
    ShowAllMovies = 27,
    ShowAllKids = 28,
    ShowAllNews = 29,
    ShowAllSports = 30,

    SearchChannels = 31,
    SearchLiveTV = 32,
    SearchMovies = 33,
    SearchShows = 34,
    SearchCastAndCrew = 35,
    Error = 36,
    ParentalControl = 37,
    Trailer = 38,
    LogInForgot = 39,
    SettingsPlayer = 40,
    LogInOkta = 41,
    ShowAllMostPopular = 42,
    ShowAllContinueWatching = 43,
    ShowAllWatchAgain = 44,
    LogInSignWays = 45,
    ShowAllTrends = 46,
    
    Root = 100,
    allOnDemand = 101,
    favChannels = 102,
    allPrograms = 103,
    DetailGenre = 104,
};
